# sign up auth
POST http://localhost:3333/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

###
# sign in auth
POST http://localhost:3333/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}
